"""Añadir orbes_totales a Usuario

Revision ID: 03576ea5e3ab
Revises: 
Create Date: 2026-04-24 13:24:23.869861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03576ea5e3ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbes_totales', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.drop_column('orbes_totales')

    # ### end Alembic commands ###
