"""Act Usuario: se crea atributo para que el servidor tenga constancia de cuando dar la recompensa al user por tiempo en la web

Revision ID: 48f9f796b427
Revises: 86d3f05aaf3e
Create Date: 2026-05-05 12:08:10.677866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f9f796b427'
down_revision = '86d3f05aaf3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_cobro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.drop_column('ultimo_cobro')

    # ### end Alembic commands ###
