"""Añadir multiplicador a Productos

Revision ID: 86d3f05aaf3e
Revises: 03576ea5e3ab
Create Date: 2026-04-29 15:53:37.359789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d3f05aaf3e'
down_revision = '03576ea5e3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiplicador', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('multiplicador')

    # ### end Alembic commands ###
